#ifndef __INC_CHARACTER_CHEST_H__
#define __INC_CHARACTER_CHEST_H__

#include "length.h"

#ifdef ENABLE_CHARACTER_CHEST

enum ECharacterChestSocket
{
	CHARACTER_CHEST_SOCKET_PID = 0,
	CHARACTER_CHEST_SOCKET_SEAL = 1,
};

enum ECharacterChestOp
{
	CHARACTER_CHEST_OP_LIST = 0,
	CHARACTER_CHEST_OP_PACK = 1,
	CHARACTER_CHEST_OP_UNPACK = 2,
	CHARACTER_CHEST_OP_PREVIEW = 3,
};

enum ECharacterChestResult
{
	CHARACTER_CHEST_OK = 0,
	CHARACTER_CHEST_ERR_WRONG_PASSWORD = 1,
	CHARACTER_CHEST_ERR_ACTIVE_CHAR = 2,
	CHARACTER_CHEST_ERR_NOT_OWNER = 3,
	CHARACTER_CHEST_ERR_ALREADY_PACKED = 4,
	CHARACTER_CHEST_ERR_INVALID_PID = 5,
	CHARACTER_CHEST_ERR_NO_EMPTY_SLOT = 6,
	CHARACTER_CHEST_ERR_NOT_PACKED = 7,
	CHARACTER_CHEST_ERR_DB = 8,
	CHARACTER_CHEST_ERR_ITEM = 9,
	CHARACTER_CHEST_ERR_ONLINE = 10,
	CHARACTER_CHEST_ERR_ALREADY_USED = 11,
};

enum ECharacterChestLogType
{
	CHARACTER_CHEST_LOG_PACK = 0,
	CHARACTER_CHEST_LOG_UNPACK = 1,
	CHARACTER_CHEST_LOG_WRONG_PASSWORD = 2,
	CHARACTER_CHEST_LOG_NO_SLOT = 3,
	CHARACTER_CHEST_LOG_INVALID_PID = 4,
};

enum ECharacterChestCGSub
{
	CHARACTER_CHEST_CG_PACK = 1,
	CHARACTER_CHEST_CG_UNPACK = 2,
	CHARACTER_CHEST_CG_PREVIEW = 3,
};

#define CHARACTER_CHEST_PREVIEW_READONLY_CELL	0xFFFF

#define CHARACTER_CHEST_ITEM_VNUM			72325
#define CHARACTER_CHEST_ALLOWED_MAP_INDEX	63
#define CHARACTER_CHEST_PACKED_ACCOUNT_ID	111111u
#define CHARACTER_CHEST_MAX_LIST			PLAYER_PER_ACCOUNT
#define CHARACTER_CHEST_MAX_PREVIEW_ITEMS	180
#define CHARACTER_CHEST_MAX_PREVIEW_SKILLS	64
#define CHARACTER_CHEST_PREVIEW_PART_COUNT	5
#define CHARACTER_CHEST_PREVIEW_SOCKET_NUM	3
#define CHARACTER_CHEST_PREVIEW_ATTR_NUM		7
#define CHARACTER_CHEST_GC_MAX_SIZE			16384
#define CHARACTER_CHEST_PASSWORD_LEN		8
#define CHARACTER_CHEST_PREVIEW_PLAYER_WIRE_SIZE	78
#define CHARACTER_CHEST_PREVIEW_PLAYER_LEGACY_SIZE	76
#define CHARACTER_CHEST_PREVIEW_PLAYER_WIRE_SIZE_V1	70
#define CHARACTER_CHEST_BIOLOGIST_LEVEL_COUNT		10

enum ECharacterChestBiologistStatus
{
	CHARACTER_CHEST_BIOLOGIST_NONE = 0,
	CHARACTER_CHEST_BIOLOGIST_PROGRESS = 1,
	CHARACTER_CHEST_BIOLOGIST_DONE = 2,
};

#pragma pack(push, 1)

typedef struct SCharacterChestPreviewSkill
{
	WORD	wVnum;
	BYTE	bMasterType;
	BYTE	bLevel;
} TCharacterChestPreviewSkill;

typedef struct SCharacterChestPreviewItem
{
	BYTE	bWindow;
	WORD	wPos;
	DWORD	dwVnum;
	DWORD	dwCount;
	long	alSockets[CHARACTER_CHEST_PREVIEW_SOCKET_NUM];
	BYTE	aAttrType[CHARACTER_CHEST_PREVIEW_ATTR_NUM];
	short	aAttrValue[CHARACTER_CHEST_PREVIEW_ATTR_NUM];
} TCharacterChestPreviewItem;

typedef struct SCharacterChestPreviewPlayer
{
	char	szName[CHARACTER_NAME_MAX_LEN + 1];
	BYTE	bJob;
	BYTE	bLevel;
	short	sST;
	short	sHT;
	short	sDX;
	short	sIQ;
	DWORD	dwExp;
	INT		iGold;
	int		iPlaytime;
	BYTE	bPartBase;
	DWORD	adwParts[CHARACTER_CHEST_PREVIEW_PART_COUNT];
	BYTE	bSkillGroup;
	INT		iCheque;
	INT		iGem;
	BYTE	bSkillCount;
} TCharacterChestPreviewPlayer;

#pragma pack(pop)

#endif
#endif
